version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak-server
    environment:
      # Admin user (required)
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin-change-me}
      
      # Basic configuration
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - keycloak-network
    restart: unless-stopped
    command: start-dev

volumes:
  keycloak_data:
    driver: local

networks:
  keycloak-network:
    driver: bridge 