name = "openadp-health-monitor"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-15"

# Environment variables (set these in Cloudflare dashboard)
[env.production.vars]
SERVERS_JSON_URL = "https://servers.openadp.org/api/servers.json"
GITHUB_REPO = "waywardgeek/servers.openadp.org"
POLL_INTERVAL_MINUTES = "5"
ERROR_THRESHOLD_PERCENT = "15"
ERROR_DURATION_MINUTES = "30"

# Secrets (set these via wrangler secret put)
# GITHUB_TOKEN = "github_pat_..."
# DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/..."

# KV namespace for storing health data
[[kv_namespaces]]
binding = "HEALTH_DATA"
id = "b8b5c346673043f482b4604d9c885249"
preview_id = "26fa6011f86341bc9c13785c65e69dde"

# Cron trigger - runs every 5 minutes
[triggers]
crons = ["*/5 * * * *"]

# Note: Custom domain health.openadp.org configured via Cloudflare dashboard 