# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import openadp_pb2 as openadp__pb2


class OpenADPStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RegisterSecret = channel.unary_unary(
        '/openadp.OpenADP/RegisterSecret',
        request_serializer=openadp__pb2.RegisterSecretRequest.SerializeToString,
        response_deserializer=openadp__pb2.RegisterSecretResponse.FromString,
        )
    self.RecoverSecret = channel.unary_unary(
        '/openadp.OpenADP/RecoverSecret',
        request_serializer=openadp__pb2.RecoverSecretRequest.SerializeToString,
        response_deserializer=openadp__pb2.RecoverSecretResponse.FromString,
        )


class OpenADPServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RegisterSecret(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RecoverSecret(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OpenADPServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RegisterSecret': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterSecret,
          request_deserializer=openadp__pb2.RegisterSecretRequest.FromString,
          response_serializer=openadp__pb2.RegisterSecretResponse.SerializeToString,
      ),
      'RecoverSecret': grpc.unary_unary_rpc_method_handler(
          servicer.RecoverSecret,
          request_deserializer=openadp__pb2.RecoverSecretRequest.FromString,
          response_serializer=openadp__pb2.RecoverSecretResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'openadp.OpenADP', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
